//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deadinside.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class playeritem
    {
        public int id { get; set; }
        [DisplayName("Player ID")]
        public int playerid { get; set; }
        [DisplayName("Item ID")]
        public int itemid { get; set; }
        [DisplayName("Item Count")]
        public int count { get; set; }
        public List<playeritem> playeritems { get; set; }
        public List<item> items { get; set; }
        public List<player> playerList { get; set; }
    }
}
