//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deadinside.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class runescapedatabaseEntities : DbContext
    {
        public runescapedatabaseEntities()
            : base("name=runescapedatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<playeritem> playeritems { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<playerstat> playerstats { get; set; }
        public virtual DbSet<skill> skills { get; set; }
    }
}
