//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deadinside.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int id { get; set; }
        public string skillname { get; set; }
        public string skilldesc { get; set; }
    }
}
